steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myimage', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/myimage']
- name: "gcr.io/cloud-builders/gke-deploy:stable"
  args:
  - run
  - --filename=KUBERNETES_CONFIG_FILE
  - --image='gcr.io/electric-clone-249408/myimage'
  - --location=us-central1-a
  - --cluster=my-k8s-cluster