---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "myapp"
  namespace: "default"
  labels:
    app: "myapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "myapp"
  template:
    metadata:
      labels:
        app: "myapp"
    spec:
      containers:
      - name: "myimage-sha256-1"
        image: "gcr.io/electric-clone-249408/myimage@sha256:9d99a18da41c95d42a30f3ca627eea3f5099dd4afef1e53743154197a01c0e73"
